- engines/aws/app/models/aws/cli.rb
The spaces and quoting were causing issues; the format submitted here is directly from the documentation[1]
[1] Example 4 https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-vpc.html
> Fix up AWS create_vpc tagging

- engines/aws/app/models/aws/allocation_address.rb
- engines/aws/app/models/aws/cli.rb
- engines/aws/app/models/aws/internet_gateway.rb
- engines/aws/app/models/aws/nat_gateway.rb
- engines/aws/app/models/aws/route_table.rb
- engines/aws/app/models/aws/subnet.rb
- engines/aws/app/models/aws/vpc.rb
- engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/cluster_size.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
- engines/rancher_on_eks/app/views/rancher_on_eks/steps/index.html.haml
The VPC Class was no longer just managing the VPC, but all of the dependent objects. This violated SRP, and overloaded the VPC, preventing it from even saving the ID if any dependent object failed.
With the steps broken out to the deployment (as steps), we can more accurately pinpoint errors and handle them.
> Move steps out of VPC to Deployment (SRP, trackability)

- app/assets/stylesheets/application.css
- db/migrate/20220324022910_add_duration_to_step.rb
- db/schema.rb
- engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
- engines/rancher_on_eks/app/views/rancher_on_eks/steps/index.html.haml
Steps are represented as proportional-width sections of the bar, based on times established through repeated deployments.
The current step's text is listed while in progress. When complete, the user is redirected to the wrapup page.
> Show a progress bar for deployment

- packaging/curated-cloud-installer.spec
- server-configs/nginx/curated-cloud-installer.conf
- Require username and password to access
the wizard
- In this case, the username is instance-id and
password is account-id
- Add python3-cloudinstancecredentials package
This Fixes #25
> Require username and password

- config/locales/en.yml
- engines/rancher_on_eks/app/controllers/rancher_on_eks/fqdn_controller.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb
- Because of the different ways the FQDN can be set up,
dropping its validation for the time being
> Remove FQDN URL validation

- engines/rancher_on_eks/config/locales/en.yml
Attempt to prevent customer permissions-issue-related errors by being explicit about requiring permissions on the Route53 zone to be used.
> Be more explicit about permissions required on Route53 zone

- app/views/layouts/_menu_item.html.haml
- engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
- engines/rancher_on_eks/app/controllers/rancher_on_eks/wrapup_controller.rb
- engines/rancher_on_eks/app/jobs/rancher_on_eks/wrapup_job.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
- Side menu not available during deployment
- Side menu not available during cleanup
- Remove errors after cleanup so rerun is possible
- Error wording in wrapup consistent
> Handle being able to re run deploy if error

- engines/rancher_on_eks/app/models/rancher_on_eks/rancher.rb
With custom fields, `release name` can be different, and `@release_name` does not work
raising an error for the command `helm uninstall '' --namespace cattle-system` with `Error: uninstall: Release name is invalid: .`
> Use ID to destroy Rancher resource

- Makefile
Since we'll never need access to the session/cookies, instead of maintaining a persistent production mode session secret, let's just generate one when when we package (we need it for the production mode asset pipeline).
> Auto-generate production mode session secret

- packaging/suse-rancher-setup.spec
- server-configs/nginx/suse-rancher-setup.conf
Instead of keeping around a self-signed TLS cert that we have to inject into the package, let's generate one at packaging.
Bonus: cert isn't named 'localhost' anymore.
> Generate self-signed TLS cert in packaging

- README.md
- bin/vc
Use the `osc`-provided `vc` command to edit changelog. No more fetching dates, no more missing whitespace.
> Manage changelog the right way

- engines/aws/app/models/aws/metadata.rb
... instead of using 'latest'. Resolves #127
```
ec2-user@ip-192-168-10-205:~> ec2metadata --api 2021-07-15 --info
{
"Code" : "Success",
"LastUpdated" : "2022-10-05T15:23:49Z",
"InstanceProfileArn" : "arn:aws:iam::[REDACTED]:instance-profile/lasso-test",
"InstanceProfileId" : "[REDACTED]"
}
ec2-user@ip-REDACTED:~> ec2metadata --api latest --info
{
"Code" : "Success",
"LastUpdated" : "2022-10-05T15:23:33Z",
"AccountId" : "[REDACTED]"
}
```
> Set the AWS IMDS API to a specific version

- engines/azure/app/models/azure/cli.rb
- engines/helm/app/models/helm/cli.rb
- engines/helm/app/models/k8s/cli.rb
- engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb
* Fix up the Helm engine to not be dependent on AWS. 
* Fix up the kubeconfig export to be more consistent with other engines.
* Finally, deploy the ingress-controller on AKS.
> AKS Workflow: step 4/8

- Gemfile
- Gemfile.lock
- app/models/tls_source.rb
- config/locales/en.yml
- engines/helm/app/models/helm/rancher.rb
- engines/rancher_on_eks/app/controllers/rancher_on_eks/security_controller.rb
- engines/rancher_on_eks/app/helpers/rancher_on_eks/authorization_helper.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
- engines/rancher_on_eks/app/views/rancher_on_eks/security/edit.html.haml
- engines/rancher_on_eks/config/routes.rb
- engines/rancher_on_eks/lib/rancher_on_eks.rb
- spec/models/rancher_spec.rb
- spec/models/tls_source_spec.rb
* New top-level TlsSource model stores TLS Source attributes with as much validation as I can manage
* Helm::Rancher model passes along TLS Source attributes as additional Helm arguments, per
https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster#5-install-rancher-with-helm-and-your-chosen-certificate-option
* New UI step: ":lock: Security Options"
UI Screenshots:
Test Result :tada: :
Resolves #118
> Option for Let's Encrypt cert on Rancher server - RancherOnEKS Workflow

- spec/models/rancher_on_aks/cluster_size_spec.rb
- spec/rails_helper.rb
- spec/vcr/az/0bf2e8cd528884785f26f49ebeed20dc
- spec/vcr/az/19f5a7cda8fcc23afb34d92d7dadc2c6
- spec/vcr/az/241c72c330ae73d551048566434bbc4c
- spec/vcr/az/3c865e051fb99ecbea9069227dbbf0b6
- spec/vcr/az/429e0ff0635e1b1f2067da7a3e626128
- spec/vcr/az/477c7881283b95b091601eb93c8a2e3e
- spec/vcr/az/4a82a6bdcb5d071bb87f32631f577787
- spec/vcr/az/4c0ce9ca01478ed4cf7936f30592f594
- spec/vcr/az/645c697de85063d5d6d5aa88c2b8c49f
- spec/vcr/az/73a863ff407877494e4022fa46989605
- spec/vcr/az/8023a27a7abe563e6016d5b24f66588c
- spec/vcr/az/8cc30952b6c6c7ff4646ae0e6ca16767
- spec/vcr/az/956bf8716fd932688024c1d67ba3ef19
- spec/vcr/az/9b5be60d907560441b6249f3533800c3
- spec/vcr/az/a340cf3d9e87f9d100a62484baf409d1
- spec/vcr/az/a7c61b2d4cb92908afb0129c854ad60d
- spec/vcr/az/c7b923e6948b393b5df3e0f1afc3021e
- spec/vcr/az/ca6dfee0d99a28abf8e4edc57e7ef305
- spec/vcr/az/cb6bb5c6a8e34cac5f130fa26283810f
- spec/vcr/az/d0bda037d4862f34b6ee7a5e479b7efe
- spec/vcr/az/d9fc2467353ff0021f76cdef6ea68287
- spec/vcr/az/e431570a5c85224a60452b6e13721a14
- spec/vcr/az/ef0773e591e0873aa1ab863cf972b5ac
- spec/vcr/az/f5f3b929224ae23ba43a28d41e14d748
- spec/vcr/az/fb754357825299ddf79a84c1b8c23a28
- spec/web_helper.rb
Speed up testing for instances in regions we already know; new recordings will automatically be made for any new regions added.
We can always do a forced recording to check for changes in existing regions.
> Use recordings for Azure instance type testing

- config/locales/en.yml
- engines/rancher_on_aks/app/controllers/rancher_on_aks/security_controller.rb
- engines/rancher_on_aks/app/helpers/rancher_on_aks/authorization_helper.rb
- engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb
- engines/rancher_on_aks/app/views/rancher_on_aks/security/edit.html.haml
- engines/rancher_on_aks/config/routes.rb
- engines/rancher_on_aks/lib/rancher_on_aks.rb
- spec/system/RancherOnAks/happy_path_spec.rb
- spec/vcr/helm/f8a12295990d8d2896bd6ccfa0e5df63
~~Depends on `azure-happy-path` branch, as the test is extended to include the security page. Do not merge until after #176 .~~
Adds security page for RancherOnAks with an option for TLS cert, rancher-generated or Let's Encrypt.
> Add Lets-Encrypt TLS option for Rancher on AKS workflow

- aws-iam/iam_role.json
- spec/vcr/aws/07ea8c672a83c7bd96a4436fff623580
I discovered an additional IAM role is required, while testing v1.2.0
> Additional IAM permission required for VPC preflight check

- config/application.rb
Most of the custom config was loaded through `yaml_config`, but the workspace got missed in the conversion. This fixes things, so _all_ custom config is loaded through the same source.
> Finish loading config from yaml_config

- app/models/concerns/deployable.rb
- app/models/step.rb
- db/migrate/20230207192140_add_cleanup_resource_to_step.rb
- db/schema.rb
- engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
I added a boolean attribute to the step, defaulting to _true_, indicating if the attached resource requires cleanup.
I then updated the deployments to indicate explicitly which steps _don't_ require cleanup. As a result of having the cleanup logic, we can go ahead and attach all the resources to the steps (getting rid of a bunch of those pesky `nil` lines).
> Steps clean up

- engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
With respect to #189 , all resources created in the run should be attached to steps.
> Consistently show resources attached to steps.

- app/controllers/application_controller.rb
- app/models/workflow.rb
- engines/pre_flight/app/controllers/pre_flight/checks_controller.rb
- engines/pre_flight/app/models/pre_flight/check.rb
- engines/rancher_on_aks/lib/rancher_on_aks.rb
- engines/rancher_on_eks/lib/rancher_on_eks.rb
Pre-flight checks were being populated when you hit the page; but this gave a false positive on authorization, as all (0) checks were passing, before that.
In order to ensure the auth works properly with pre-flight checks, check against an expected count provided by the workflow.
> Preflight check count

- engines/aws/app/models/aws/cluster.rb
- engines/aws/app/models/aws/kubeconfig.rb
- engines/azure/app/models/azure/kubeconfig.rb
- engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb
- engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
When we cleanup, the method for exporting kubeconfig can be included.
> Handle kubeconfig as a resource for easier cleanup

- .github/workflows/rails-testing.yml
- engines/aws/app/models/aws/region.rb
AWS-CLI needs a region to load regions from ;-)
With the refactor of AWS::Cli onto Executable, the default region from AWS::Region wasn't being communicated. This is resolved by explicitly setting a default region onto the CLI instance in AWS::Region.
> Explicitly set a region when loading AWS regions (bsc#1209066)

- app/controllers/login_controller.rb
- engines/aws/app/controllers/aws/permissions_controller.rb
- engines/azure/app/controllers/azure/logins_controller.rb
- engines/rancher_on_aks/app/controllers/rancher_on_aks/steps_controller.rb
- engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
Flash messages are stored in the session; in Lasso's case the session is stored in a cookie, and therefore limited to a maximum of 4K. If an error message is excessively long, it can cause a cookie overflow error, blow the session, and force Rails to throw a 500 Application Error, which loses the original error posted to the flash. Better to preserve a smaller portion of the error (a 1000 characters should be enough) than lose it altogether.
> Limit flash error message sizes to not overflow cookie session
