SUSE-Enceladus/suse-rancher-setup

engines/aws/app/controllers/aws/node_group.rb
engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/node-role-trust-policy.json
engines/aws/app/models/aws/role.rb
engines/aws/app/models/aws/vpc.rb
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb

- Add route between route-tables and nat gateway
- Add route between route-tables and internet gateway
- Create role for nodegroup
- Create nodegroup

Add nodegroup step

---

engines/aws/app/models/aws/region.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/fqdn_controller.rb
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb
engines/rancher_on_eks/app/views/rancher_on_eks/fqdn/edit.html.haml
engines/rancher_on_eks/config/locales/en.yml
engines/rancher_on_eks/config/routes.rb
engines/rancher_on_eks/lib/rancher_on_eks.rb

UI & handler for FQDN value

---

.bumpversion.cfg
config/locales/en.yml
engines/aws/app/controllers/aws/credentials_controller.rb
engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/credential.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/fqdn_controller.rb
engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb
lib/curated_cloud_installer.rb
packaging/curated-cloud-installer.spec

- Add AWS credentials validation
- Add FQDN and subdomain validation
This Fixes #21

Validations

---

app/assets/stylesheets/application.css
app/helpers/authorization_helper.rb
app/views/layouts/_menu_item.html.haml

Add navigation order

---

app/helpers/authorization_helper.rb
engines/aws/app/controllers/aws/regions_controller.rb
engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/region.rb
engines/aws/config/locales/en.yml
engines/rancher_on_eks/app/models/rancher_on_eks/cluster_size.rb

Some regions do not have AZs for the default instance types
This adds a fallback to m5 then m4 if that should fail.
This Fixes #30

Update region validation

---

engines/aws/app/models/aws/cli.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/wrapup_controller.rb

- Delete file before create a new one
- Bring back the file path
- Enable generation of commands when new deployment

Better handling command file

---

config/application.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/steps_controller.rb
engines/rancher_on_eks/app/jobs/rancher_on_eks/deployer_job.rb

- Add deployment raised error in the UI
- Deployment stops, no resource created
after error

Show CLI error in the UI when deploying

---

engines/aws/app/models/aws/cli.rb
engines/rancher_on_eks/app/jobs/rancher_on_eks/deployer_job.rb

- Raise Standarderror exception

Raise create nodegroup exception

---

app/models/resource.rb
engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/region.rb

- Raise exception when command ran successfully but operation status failed
- Raise exception when command returned error

Raise exception when stderr is present

---

engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/vpc.rb

- Enable DNS support
- Enable DNS Hostnames

Modify VPC attributes

---

app/models/resource.rb
engines/rancher_on_eks/app/controllers/rancher_on_eks/wrapup_controller.rb
engines/rancher_on_eks/app/jobs/rancher_on_eks/deployer_job.rb
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
engines/rancher_on_eks/app/views/rancher_on_eks/wrapup/show.html.haml
engines/rancher_on_eks/config/locales/en.yml

- Raise an exception if a resource is in a failed state
when the command was run successfully
- Stop Deployment stop
- User can recover and clean up all the created resources

Handle failed command ran successfully

---

engines/aws/app/models/aws/cli.rb
engines/helm/app/models/helm/cli.rb
engines/helm/app/models/k8s/cli.rb

- Log the command to be run
- Log the stdout and stderr of the command ran
This Fixes #49

Add command logging

---

app/models/resource.rb
config/application.rb
engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/dns_record.rb

- Update user friendly resources in error
- Update DNS record file path

Fixes based on tests

---

engines/rancher_on_eks/config/locales/en.yml

+ Fix the link to the IAM role json which was relocated.
+ Fixes #84

Fix link to IAM role config

---

engines/aws/app/views/aws/regions/edit.html.haml

Update button text to Next instead of Save

---

engines/aws/app/models/aws/cli.rb

Remove AWS credentials envs

---

app/helpers/authorization_helper.rb
config/application.rb
engines/aws/app/views/aws/permissions/show.html.haml

Fix permission check

---

config/application.rb
config/config.yml.example
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb

Move kubernetes version to deploy, to external config

---

aws-iam/iam_role.json

re: https://bugzilla.suse.com/show_bug.cgi?id=1203298

Add an additional permission

---

config/application.rb
engines/aws/app/views/aws/regions/edit.html.haml
engines/aws/app/views/aws/steps/new.html.haml
engines/rancher_on_eks/app/helpers/rancher_on_eks/authorization_helper.rb
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
engines/rancher_on_eks/app/views/rancher_on_eks/fqdn/edit.html.haml
engines/rancher_on_eks/app/views/rancher_on_eks/steps/index.html.haml
engines/rancher_on_eks/config/locales/en.yml
engines/shirt_size/app/views/shirt_size/sizes/edit.html.haml

The authorization refactor missed non-UI endpoints (so you couldn't submit forms), so that's fixed now.
Navigation had gotten inconsistent, with different labels and positions. Now, every step after _login_ uses Back/Next buttons at the bottom of the content.

Fix up authorization and navigation

---

engines/rancher_on_eks/app/views/rancher_on_eks/wrapup/show.html.haml
engines/rancher_on_eks/config/locales/en.yml

Add a link to Rancher's update instructions.

---

engines/aws/app/models/aws/cli.rb
engines/aws/app/models/aws/dns_record.rb

Generate delete command for route53 DNS record

---

app/controllers/application_controller.rb
app/controllers/login_controller.rb
app/models/user.rb
test/controllers/welcome_controller_test.rb
test/test_helper.rb

Move user authorization token to user session (cookie)

---

engines/azure/app/models/azure/cli.rb
engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb

Use Azure-cli to fetch the _kubeconfig_ for the AKS cluster created in step 2.

AKS Workflow: step 3/8

---

engines/azure/app/models/azure/cli.rb
engines/azure/app/models/azure/cluster.rb
engines/azure/app/models/azure/load_balancer.rb
engines/azure/app/models/azure/public_ip.rb
engines/azure/app/models/azure/resource_group.rb
engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb

Fetching the Public IP address associated with the cluster's load balancer (and a little refactoring)

AKS Workflow: step 5/8

---

engines/azure/app/models/azure/cli.rb
engines/azure/app/models/azure/dns_record.rb
engines/azure/app/models/azure/public_ip.rb
engines/azure/app/models/azure/resource_group.rb
engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb

A couple of small changes in support of writing the DNS record.

AKS Workflow: step 6/8

---

app/views/layouts/steps/_resource_list.html.haml
config/locales/en.yml
engines/azure/app/models/azure/dns_record.rb
engines/azure/app/models/azure/resource_group.rb
engines/helm/app/models/helm/cert_manager.rb
engines/helm/app/models/helm/helm_resource.rb
engines/helm/app/models/helm/ingress_controller.rb
engines/helm/app/models/helm/rancher.rb
engines/rancher_on_aks/app/controllers/rancher_on_aks/steps_controller.rb
engines/rancher_on_aks/app/controllers/rancher_on_aks/wrapup_controller.rb
engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb
engines/rancher_on_aks/app/models/rancher_on_aks/fqdn.rb
engines/rancher_on_aks/app/views/rancher_on_aks/steps/index.html.haml
engines/rancher_on_aks/app/views/rancher_on_aks/wrapup/show.html.haml
engines/rancher_on_eks/app/controllers/rancher_on_eks/wrapup_controller.rb
engines/rancher_on_eks/app/models/rancher_on_eks/deployment.rb
engines/rancher_on_eks/app/views/rancher_on_eks/steps/index.html.haml
engines/rancher_on_eks/app/views/rancher_on_eks/wrapup/show.html.haml
spec/models/rancher_spec.rb

... and it was time to populate the wrapup page and do some fixes to enable (in-code) rollback. UI-based rollback ("clean up") to follow.

AKS Deployment: steps 7 and 8/8

---

app/helpers/application_helper.rb
app/views/layouts/steps/_resource_list.html.haml
config/locales/en.yml
engines/aws/app/views/aws/cli/new.html.haml
engines/aws/app/views/aws/permissions/show.html.haml
engines/rancher_on_aks/app/views/rancher_on_aks/wrapup/show.html.haml
engines/rancher_on_eks/app/views/rancher_on_eks/wrapup/show.html.haml

I set out to enable single line breaks for the wrapup page, but there were a few other cleanups that came up along the way.

Markdown cleanup

---

app/assets/stylesheets/application.css
app/views/layouts/_feedback.html.haml
app/views/layouts/_footer.html.haml
app/views/layouts/application.html.haml
config/locales/en.yml

Feedback modal

---

app/helpers/application_helper.rb
spec/system/RancherOnEks/happy_path_spec.rb
spec/web_helper.rb

Leave sidebar items disabled after deployment is done

---

config/locales/en.yml
engines/rancher_on_eks/app/controllers/rancher_on_eks/wrapup_controller.rb
engines/rancher_on_eks/app/jobs/rancher_on_eks/wrapup_job.rb
engines/rancher_on_eks/app/views/rancher_on_eks/wrapup/show.html.haml

When cleaning up resources, if the deletion of any failed then inform the user in the UI and stop the process
This Fixes #121

Stop wrapup/cleanup process if error

---

app/helpers/application_helper.rb
config/environments/production.rb

Two issues I discovered while testing v.1.2.1

1.2.1 fixes

---

config/locales/en.yml

The text was originally copied from AWS, but Azure takes significantly less time.

Azure takes less than 10 minutes

---

app/models/concerns/executable.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
engines/aws/app/models/aws/cli.rb
engines/azure/app/models/azure/cli.rb
engines/helm/app/models/helm/cli.rb
engines/helm/app/models/k8s/cli.rb
spec/models/executable_spec.rb

Getting some consistency into the behavior of the CLI classes. I have some WIP that builds on this to handle capturing commands in a more consistent way.

CLI refactor

---

config/locales/en.yml
engines/rancher_on_aks/app/controllers/rancher_on_aks/wrapup_controller.rb
engines/rancher_on_aks/app/views/rancher_on_aks/wrapup/success.html.haml

... in prep for having a 'failure' view.

Move main wrapup view to 'success'

---

app/views/layouts/steps/_resource_list.html.haml
config/locales/en.yml

... so the title & caption can be displayed, even if there is an empty list.
(You can always render the partial conditionally to replicate the old behavior)

Move conditional in resources list

---

engines/azure/app/models/azure/cli.rb
engines/azure/app/models/azure/cluster.rb
engines/rancher_on_aks/app/models/rancher_on_aks/deployment.rb

Issues found in the older version of _az_ shipped with SLES.

Fixes for Azure-CLI v2.17
